# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 14:05
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', blog.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='new', max_length=30),
            preserve_default=False,
        ),
    ]
